title: Ouistiti
theme: jekyll-theme-tactile
show_downloads: true
url: "https://ouistiti-project.github.io"
baseurl: "/ouistiti"

github:
  public: true
  is_project_page: true
  repository_url: "https://github.com/ouistiti-project/ouistiti"
  tar_url: "https://github.com/ouistiti-project/ouistiti/archive/ouistiti-latest.tar.gz"
github_profile: "https://github.com/ouistiti-project"

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
