name: Build
on:
  push:
    branches:
      - master
    paths:
      - "*.c"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  sources:
    name: ubuntu deb
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: ouistiti_${{vars.VERSION}}
      DEPENDENCIES: libjansson-dev libconfig-dev libssl-dev devscripts
    steps:
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install $DEPENDENCIES
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: source archive
        run: |
          cp -r packages/debian .
          tar -C .. -czf ../${{env.PACKAGENAME}}.orig.tar.gz --exclude=packages --exclude=www --exclude=.git* --exclude=*sonarcloud* --exclude=.travis.yml ouistiti
          mv ../${{env.PACKAGENAME}}.orig.tar.gz .
      - name: source artifact
        uses: actions/upload-artifact@v3
        with:
          name: sources
          path: ${{env.PACKAGENAME}}.orig.tar.gz
  binaries:
    name: ubuntu deb
    needs: sources
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: ouistiti_${{vars.VERSION}}
      DEPENDENCIES: libjansson-dev libconfig-dev libssl-dev devscripts
    steps:
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install $DEPENDENCIES
      - name: download sources
        uses: actions/download-artifact@v3
        with:
          name: sources_archive
      - name: unpack sources
        run: |
          tar -xzf ${{env.PACKAGENAME}}.orig.tar.gz
          cd ouistiti
      - name: debuild
        run: |
          debuild -i -uc -us
      - name: binaries artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ../ouistiti*${{vars.VERSION}}*.deb
