name: Packaging
on:
  workflow_dispatch:
jobs:
  sources:
    name: ubuntu deb
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: ouistiti
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: cache
        uses: actions/cache@v3
        with:
          path: /tmp/version.txt
          key: version
      - name: version
        id: version
        run: |
          echo "VERSION=$(make version | awk '{print $2}')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(make version | awk '{print $2}')" >> "/tmp/version.txt"
      - name: source archive
        run: |
          cp -r packages/debian .
          tar -C .. -czf ../${{env.PACKAGENAME}}_${{steps.version.outputs.VERSION}}.orig.tar.gz --exclude=packages --exclude=www --exclude=.git* --exclude=*sonarcloud* --exclude=.travis.yml ouistiti
          mv ../${{env.PACKAGENAME}}.orig.tar.gz .
      - name: source artifact
        uses: actions/upload-artifact@v3
        with:
          name: sources
          path: ${{env.PACKAGENAME}}.orig.tar.gz
  binaries:
    name: ubuntu deb
    needs: sources
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: ouistiti
      DEPENDENCIES: libjansson-dev libconfig-dev libssl-dev devscripts
    steps:
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install $DEPENDENCIES
      - name: download sources
        uses: actions/download-artifact@v3
        with:
          name: sources
      - name: cache
        uses: actions/cache@v3
        with:
          path: /tmp/version.txt
          key: version
      - name: version
        id: version
        run: |
          cat /tmp/version.txt >> "$GITHUB_OUTPUT"
      - name: unpack sources
        run: |
          tar -xzf ${{env.PACKAGENAME}}_${{steps.version.outputs.VERSION}}.orig.tar.gz
          cd ouistiti
      - name: debuild
        run: |
          debuild -i -uc -us
      - name: binaries artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ../ouistiti*${{vars.VERSION}}*.deb
